package:
  format-version: "1.0.0"
  name: "wireless_rnbd"
  type: "api"
  status: "beta"
  required: false
  version: "v2.0.4"

  dependencies:
    - name: "crypto"
      type: "package"
      version: "v3.8.2"
    - name: "core"
      type: "package"
      version: "v3.14.0"
    - name: "csp"
      type: "package"
      version: "v3.20.0"
    - name: "bsp"
      type: "package"
      version: "v3.21.1"
    - name: "net"
      type: "package"
      version: "v3.13.0"
