package:
  format-version: "1.1.0"
  name: "wireless_rnbd"
  type: "api"
  status: "beta"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "crypto"
      type: "package"
      version: "3.8.0"
    - name: "core"
      type: "package"
      version: "3.13.1"
    - name: "csp"
      type: "package"
      version: "3.18.0"
    - name: "bsp"
      type: "package"
      version: "3.17.0"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "10.3.1"
    - name: "dev_packs"
      type: "package"
      version: "3.18.0"
    - name: "net"
      type: "package"
      version: "3.10.1"
