package:
  format-version: "1.0.0"
  name: "wireless_rnbd"
  type: "api"
  status: "beta"
  required: false
  version: "v2.0.3"

  dependencies:
    - name: "crypto"
      type: "package"
      version: "v3.8.1"
    - name: "core"
      type: "package"
      version: "v3.13.4"
    - name: "csp"
      type: "package"
      version: "v3.19.1"
    - name: "bsp"
      type: "package"
      version: "v3.20.1"
    - name: "net"
      type: "package"
      version: "v3.10.1"
